<?php

namespace App\Services;

use Illuminate\Support\Facades\DB;
use PDO;
use RuntimeException;

class DatabaseBackupService
{
    protected int $insertBatchSize = 200;

    public function dump(callable $writer): void
    {
        $connection = DB::connection();
        $driver = $connection->getDriverName();

        if ($driver !== 'mysql') {
            throw new RuntimeException("Backup hanya didukung untuk MySQL/MariaDB. Driver aktif: {$driver}.");
        }

        $database = $connection->getDatabaseName();
        $pdo = $connection->getPdo();

        $writer("-- ========================================\n");
        $writer("-- Backup database: {$database}\n");
        $writer("-- Generated at: " . now()->toDateTimeString() . "\n");
        $writer("-- Generated by: po-workflow superadmin backup\n");
        $writer("-- ========================================\n\n");

        $writer("SET NAMES utf8mb4;\n");
        $writer("SET FOREIGN_KEY_CHECKS = 0;\n");
        $writer("SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n");
        $writer("SET time_zone = '+00:00';\n\n");

        $tableKey = "Tables_in_{$database}";
        $tables = $pdo->query('SHOW FULL TABLES')->fetchAll(PDO::FETCH_ASSOC);

        foreach ($tables as $row) {
            $name = $row[$tableKey] ?? array_values($row)[0];
            $type = $row['Table_type'] ?? 'BASE TABLE';

            if ($type === 'BASE TABLE') {
                $this->dumpTable($pdo, $name, $writer);
            }
        }

        foreach ($tables as $row) {
            $name = $row[$tableKey] ?? array_values($row)[0];
            $type = $row['Table_type'] ?? 'BASE TABLE';

            if ($type === 'VIEW') {
                $this->dumpView($pdo, $name, $writer);
            }
        }

        $writer("\nSET FOREIGN_KEY_CHECKS = 1;\n");
    }

    protected function dumpTable(PDO $pdo, string $table, callable $writer): void
    {
        $writer("\n-- ----------------------------\n");
        $writer("-- Table structure: `{$table}`\n");
        $writer("-- ----------------------------\n");
        $writer("DROP TABLE IF EXISTS `{$table}`;\n");

        $createRow = $pdo->query("SHOW CREATE TABLE `{$table}`")->fetch(PDO::FETCH_ASSOC);
        $createSql = $createRow['Create Table'] ?? '';
        if ($createSql !== '') {
            $writer($createSql . ";\n\n");
        }

        $writer("-- Data: `{$table}`\n");
        $stmt = $pdo->query("SELECT * FROM `{$table}`");
        if ($stmt === false) {
            return;
        }

        $columns = null;
        $batch = [];

        while ($dataRow = $stmt->fetch(PDO::FETCH_ASSOC)) {
            if ($columns === null) {
                $columns = array_keys($dataRow);
            }

            $batch[] = $this->formatValuesTuple($pdo, $dataRow);

            if (count($batch) >= $this->insertBatchSize) {
                $writer($this->buildInsertStatement($table, $columns, $batch));
                $batch = [];
            }
        }

        if (!empty($batch) && $columns !== null) {
            $writer($this->buildInsertStatement($table, $columns, $batch));
        }

        $writer("\n");
    }

    protected function dumpView(PDO $pdo, string $view, callable $writer): void
    {
        $writer("\n-- ----------------------------\n");
        $writer("-- View: `{$view}`\n");
        $writer("-- ----------------------------\n");
        $writer("DROP VIEW IF EXISTS `{$view}`;\n");

        $createRow = $pdo->query("SHOW CREATE VIEW `{$view}`")->fetch(PDO::FETCH_ASSOC);
        $createSql = $createRow['Create View'] ?? '';
        if ($createSql !== '') {
            $writer($createSql . ";\n");
        }
    }

    protected function buildInsertStatement(string $table, array $columns, array $tuples): string
    {
        $columnList = implode(',', array_map(fn ($c) => "`{$c}`", $columns));
        return "INSERT INTO `{$table}` ({$columnList}) VALUES\n" . implode(",\n", $tuples) . ";\n";
    }

    protected function formatValuesTuple(PDO $pdo, array $row): string
    {
        $values = [];
        foreach ($row as $value) {
            $values[] = $this->formatValue($pdo, $value);
        }
        return '(' . implode(',', $values) . ')';
    }

    protected function formatValue(PDO $pdo, mixed $value): string
    {
        if ($value === null) {
            return 'NULL';
        }
        if (is_bool($value)) {
            return $value ? '1' : '0';
        }
        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }

        return $pdo->quote((string) $value);
    }

    public function restore(string $sqlPath): void
    {
        if (app()->environment('production')) {
            throw new RuntimeException('Restore tidak diperbolehkan di environment production.');
        }

        if (!is_file($sqlPath)) {
            throw new RuntimeException("File restore tidak ditemukan: {$sqlPath}");
        }

        $sql = $this->isGzipFile($sqlPath)
            ? $this->readGzipFile($sqlPath)
            : file_get_contents($sqlPath);

        if ($sql === false || $sql === '') {
            throw new RuntimeException('File restore kosong atau tidak terbaca.');
        }

        DB::unprepared($sql);
    }

    protected function isGzipFile(string $path): bool
    {
        $handle = fopen($path, 'rb');
        if ($handle === false) {
            return false;
        }

        $magic = fread($handle, 2);
        fclose($handle);

        return $magic === "\x1f\x8b";
    }

    protected function readGzipFile(string $path): string
    {
        $handle = gzopen($path, 'rb');
        if ($handle === false) {
            throw new RuntimeException('Gagal membuka file gzip.');
        }

        $contents = '';
        while (!gzeof($handle)) {
            $chunk = gzread($handle, 1024 * 1024);
            if ($chunk === false) {
                gzclose($handle);
                throw new RuntimeException('Gagal membaca file gzip.');
            }
            $contents .= $chunk;
        }
        gzclose($handle);

        return $contents;
    }
}
