<?php

namespace App\Services;

use Generator;
use Illuminate\Support\Facades\DB;
use PDO;
use RuntimeException;
use Throwable;

class DatabaseBackupService
{
    protected int $insertBatchSize = 200;

    public function dump(callable $writer): void
    {
        $connection = DB::connection();
        $driver = $connection->getDriverName();

        if ($driver !== 'mysql') {
            throw new RuntimeException("Backup hanya didukung untuk MySQL/MariaDB. Driver aktif: {$driver}.");
        }

        $database = $connection->getDatabaseName();
        $pdo = $connection->getPdo();

        // PDO buffers an entire MySQL result set in PHP memory by default, so the
        // row-by-row loop below would still load a whole table before writing a
        // single byte. Fetch unbuffered for the duration of the dump instead.
        $wasBuffered = true;
        try {
            $wasBuffered = (bool) $pdo->getAttribute(PDO::MYSQL_ATTR_USE_BUFFERED_QUERY);
        } catch (Throwable) {
            // Driver does not expose the attribute; assume the default.
        }
        $pdo->setAttribute(PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, false);

        try {
            $writer("-- ========================================\n");
            $writer("-- Backup database: {$database}\n");
            $writer('-- Generated at: '.now()->toDateTimeString()."\n");
            $writer("-- Generated by: po-workflow superadmin backup\n");
            $writer("-- ========================================\n\n");

            $writer("SET NAMES utf8mb4;\n");
            $writer("SET FOREIGN_KEY_CHECKS = 0;\n");
            $writer("SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n");
            $writer("SET time_zone = '+00:00';\n\n");

            $tableKey = "Tables_in_{$database}";
            $tablesStmt = $pdo->query('SHOW FULL TABLES');
            $tables = $tablesStmt->fetchAll(PDO::FETCH_ASSOC);
            $tablesStmt->closeCursor();

            foreach ($tables as $row) {
                $name = $row[$tableKey] ?? array_values($row)[0];
                $type = $row['Table_type'] ?? 'BASE TABLE';

                if ($type === 'BASE TABLE') {
                    $this->dumpTable($pdo, $name, $writer);
                }
            }

            foreach ($tables as $row) {
                $name = $row[$tableKey] ?? array_values($row)[0];
                $type = $row['Table_type'] ?? 'BASE TABLE';

                if ($type === 'VIEW') {
                    $this->dumpView($pdo, $name, $writer);
                }
            }

            $writer("\nSET FOREIGN_KEY_CHECKS = 1;\n");
        } finally {
            $pdo->setAttribute(PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, $wasBuffered);
        }
    }

    protected function dumpTable(PDO $pdo, string $table, callable $writer): void
    {
        $writer("\n-- ----------------------------\n");
        $writer("-- Table structure: `{$table}`\n");
        $writer("-- ----------------------------\n");
        $writer("DROP TABLE IF EXISTS `{$table}`;\n");

        $createStmt = $pdo->query("SHOW CREATE TABLE `{$table}`");
        $createRow = $createStmt->fetch(PDO::FETCH_ASSOC);
        // An unbuffered statement stays active until its cursor is closed and
        // would otherwise block the next query on this connection.
        $createStmt->closeCursor();

        $createSql = $createRow['Create Table'] ?? '';
        if ($createSql !== '') {
            $writer($createSql.";\n\n");
        }

        $writer("-- Data: `{$table}`\n");
        $stmt = $pdo->query("SELECT * FROM `{$table}`");
        if ($stmt === false) {
            return;
        }

        $columns = null;
        $batch = [];

        while ($dataRow = $stmt->fetch(PDO::FETCH_ASSOC)) {
            if ($columns === null) {
                $columns = array_keys($dataRow);
            }

            $batch[] = $this->formatValuesTuple($pdo, $dataRow);

            if (count($batch) >= $this->insertBatchSize) {
                $writer($this->buildInsertStatement($table, $columns, $batch));
                $batch = [];
            }
        }

        $stmt->closeCursor();

        if (! empty($batch) && $columns !== null) {
            $writer($this->buildInsertStatement($table, $columns, $batch));
        }

        $writer("\n");
    }

    protected function dumpView(PDO $pdo, string $view, callable $writer): void
    {
        $writer("\n-- ----------------------------\n");
        $writer("-- View: `{$view}`\n");
        $writer("-- ----------------------------\n");
        $writer("DROP VIEW IF EXISTS `{$view}`;\n");

        $createStmt = $pdo->query("SHOW CREATE VIEW `{$view}`");
        $createRow = $createStmt->fetch(PDO::FETCH_ASSOC);
        $createStmt->closeCursor();

        $createSql = $createRow['Create View'] ?? '';
        if ($createSql !== '') {
            $writer($createSql.";\n");
        }
    }

    protected function buildInsertStatement(string $table, array $columns, array $tuples): string
    {
        $columnList = implode(',', array_map(fn ($c) => "`{$c}`", $columns));

        return "INSERT INTO `{$table}` ({$columnList}) VALUES\n".implode(",\n", $tuples).";\n";
    }

    protected function formatValuesTuple(PDO $pdo, array $row): string
    {
        $values = [];
        foreach ($row as $value) {
            $values[] = $this->formatValue($pdo, $value);
        }

        return '('.implode(',', $values).')';
    }

    protected function formatValue(PDO $pdo, mixed $value): string
    {
        if ($value === null) {
            return 'NULL';
        }
        if (is_bool($value)) {
            return $value ? '1' : '0';
        }
        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }

        return $pdo->quote((string) $value);
    }

    public function restore(string $sqlPath): void
    {
        if (app()->environment('production')) {
            throw new RuntimeException('Restore tidak diperbolehkan di environment production.');
        }

        if (! is_file($sqlPath)) {
            throw new RuntimeException("File restore tidak ditemukan: {$sqlPath}");
        }

        $executed = 0;

        foreach ($this->statements($sqlPath) as $statement) {
            DB::unprepared($statement);
            $executed++;
        }

        if ($executed === 0) {
            throw new RuntimeException('File restore kosong atau tidak terbaca.');
        }
    }

    /**
     * Streams the dump file and yields one complete SQL statement at a time.
     *
     * Reading the decompressed dump into a single string is what exhausted the
     * memory limit: the string itself, the copy PHP makes each time it grows,
     * and a third copy when the whole thing is handed to the driver. Here only
     * the statement currently being assembled is ever held in memory.
     *
     * The scan is a small state machine because a `;` only separates statements
     * when it is not inside a quoted literal, a quoted identifier, or a comment.
     */
    protected function statements(string $path): Generator
    {
        $isGzip = $this->isGzipFile($path);
        $handle = $isGzip ? gzopen($path, 'rb') : fopen($path, 'rb');

        if ($handle === false) {
            throw new RuntimeException('Gagal membuka file restore.');
        }

        $buffer = '';
        $quote = null;              // active ' " or ` delimiter, null when outside one
        $inBlockComment = false;

        try {
            while (($line = $isGzip ? gzgets($handle) : fgets($handle)) !== false) {
                $length = strlen($line);

                for ($i = 0; $i < $length; $i++) {
                    $char = $line[$i];
                    $next = $line[$i + 1] ?? '';

                    if ($quote !== null) {
                        $buffer .= $char;

                        // Backslash escapes apply inside string literals (MySQL's
                        // PDO::quote emits them), never inside `identifiers`.
                        if ($char === '\\' && $quote !== '`' && $next !== '') {
                            $buffer .= $next;
                            $i++;

                            continue;
                        }

                        if ($char === $quote) {
                            if ($next === $quote) {
                                // A doubled delimiter ('') stays inside the literal.
                                $buffer .= $next;
                                $i++;

                                continue;
                            }
                            $quote = null;
                        }

                        continue;
                    }

                    if ($inBlockComment) {
                        $buffer .= $char;
                        if ($char === '*' && $next === '/') {
                            $buffer .= $next;
                            $i++;
                            $inBlockComment = false;
                        }

                        continue;
                    }

                    // Line comment (`#` or `-- `): nothing executable follows on this line.
                    $isDashComment = $char === '-'
                        && $next === '-'
                        && in_array($line[$i + 2] ?? "\n", [' ', "\t", "\r", "\n"], true);

                    if ($char === '#' || $isDashComment) {
                        break;
                    }

                    // Block comments are kept: MySQL conditional comments
                    // (/*!40000 ALTER TABLE ... */) are executable statements.
                    if ($char === '/' && $next === '*') {
                        $buffer .= '/*';
                        $i++;
                        $inBlockComment = true;

                        continue;
                    }

                    if ($char === "'" || $char === '"' || $char === '`') {
                        $quote = $char;
                        $buffer .= $char;

                        continue;
                    }

                    if ($char === ';') {
                        $statement = trim($buffer);
                        $buffer = '';
                        if ($statement !== '') {
                            yield $statement;
                        }

                        continue;
                    }

                    $buffer .= $char;
                }

                if ($buffer !== '') {
                    $buffer .= "\n";
                }
            }
        } finally {
            $isGzip ? gzclose($handle) : fclose($handle);
        }

        // A trailing statement whose closing semicolon is missing.
        $statement = trim($buffer);
        if ($statement !== '') {
            yield $statement;
        }
    }

    protected function isGzipFile(string $path): bool
    {
        $handle = fopen($path, 'rb');
        if ($handle === false) {
            return false;
        }

        $magic = fread($handle, 2);
        fclose($handle);

        return $magic === "\x1f\x8b";
    }
}
